# Generated by Django 4.2.6 on 2023-10-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hosp_Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Location', models.CharField(blank=True, max_length=300, null=True)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Hosp_Image', models.ImageField(blank=True, null=True, upload_to='Hospital Image')),
            ],
        ),
    ]
