# Generated by Django 4.2.6 on 2023-10-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('Hospital', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('Medicalid', models.CharField(blank=True, max_length=100, null=True)),
                ('Username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Medical', models.ImageField(blank=True, null=True, upload_to='MedicalID')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='DoctorPhoto')),
            ],
        ),
    ]
