# Generated by Django 4.2.6 on 2023-10-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=10, null=True)),
                ('LName', models.CharField(blank=True, max_length=10, null=True)),
                ('Username', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('Password', models.CharField(blank=True, max_length=10, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Address', models.CharField(blank=True, max_length=10, null=True)),
                ('Mobile', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/Donor/')),
            ],
        ),
    ]
