# Generated by Django 4.2.6 on 2023-11-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0002_patientdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='patientdb',
            name='Username',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
