# Generated by Django 4.2.6 on 2023-11-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0004_medicinedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
