# Generated by Django 4.2.6 on 2023-11-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0006_patientmedicinedb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientMedicineDB',
            new_name='PatientMedicineDetailsDB',
        ),
    ]
