# Generated by Django 4.2.6 on 2023-11-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0007_rename_patientmedicinedb_patientmedicinedetailsdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetailsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine', models.CharField(blank=True, max_length=100, null=True)),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Morning', models.CharField(blank=True, max_length=100, null=True)),
                ('Afternoon', models.CharField(blank=True, max_length=100, null=True)),
                ('Night', models.CharField(blank=True, max_length=100, null=True)),
                ('Day', models.IntegerField(blank=True, null=True)),
                ('Message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
