# Generated by Django 4.2.6 on 2023-11-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0008_patientdetailsdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientMedicineDetailsDB',
            new_name='patientmedicinedb',
        ),
    ]
