# Generated by Django 4.2.6 on 2023-11-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0009_rename_patientmedicinedetailsdb_patientmedicinedb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patientmedicinedb',
        ),
    ]
