# Generated by Django 4.2.6 on 2023-11-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0011_hospitalnewdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='User',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
