# Generated by Django 4.2.6 on 2023-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0012_doctordb_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedb',
            name='Doctor_User',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicinedb',
            name='Hospital_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
