# Generated by Django 4.2.6 on 2023-11-28 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0013_medicinedb_doctor_user_medicinedb_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetailsdb',
            name='Doctor_User',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientdetailsdb',
            name='Hospital_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientdetailsdb',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 14, 30, 47, 430111)),
        ),
    ]
