# Generated by Django 4.2.6 on 2023-11-28 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0014_patientdetailsdb_doctor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetailsdb',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 14, 32, 22, 855243)),
        ),
    ]
