# Generated by Django 4.2.6 on 2023-11-28 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0017_alter_patientdetailsdb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedb',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 14, 35, 2, 134787)),
        ),
        migrations.AlterField(
            model_name='patientdetailsdb',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 14, 35, 2, 135865)),
        ),
    ]
