# Generated by Django 4.2.6 on 2023-11-28 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0018_medicinedb_date_alter_patientdetailsdb_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPrescriptionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, max_length=100, null=True)),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Hospital_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Doctor_User', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='medicinedb',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 20, 39, 58, 373532)),
        ),
        migrations.AlterField(
            model_name='patientdetailsdb',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 20, 39, 58, 377192)),
        ),
    ]
