# Generated by Django 4.2.6 on 2023-11-28 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0019_labprescriptiondb_alter_medicinedb_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedb',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 20, 40, 57, 414553)),
        ),
        migrations.AlterField(
            model_name='patientdetailsdb',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 20, 40, 57, 414553)),
        ),
    ]
