# Generated by Django 4.2.6 on 2023-11-28 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0020_alter_medicinedb_date_alter_patientdetailsdb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedb',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 20, 41, 36, 698519)),
        ),
        migrations.AlterField(
            model_name='patientdetailsdb',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 20, 41, 36, 699544)),
        ),
    ]
