# Generated by Django 4.2.6 on 2023-11-28 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0021_alter_medicinedb_date_alter_patientdetailsdb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedb',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 20, 42, 18, 908836)),
        ),
        migrations.AlterField(
            model_name='patientdetailsdb',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 28, 20, 42, 18, 908836)),
        ),
    ]
