# Generated by Django 4.2.6 on 2023-11-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0023_alter_medicinedb_date_alter_patientdetailsdb_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPrescriptionHistoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, max_length=100, null=True)),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Hospital_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Doctor_User', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
