# Generated by Django 4.2.6 on 2023-12-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0024_labprescriptionhistorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReportsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report', models.FileField(blank=True, null=True, upload_to='Documents_Report')),
                ('P_Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Hospital_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Hospital_UserName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
