# Generated by Django 4.2.6 on 2023-12-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0025_labreportsdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreportsdb',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
