# Generated by Django 4.2.6 on 2023-12-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0026_labreportsdb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprescriptionhistorydb',
            name='Report',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='labprescriptionhistorydb',
            name='Status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='labprescriptionhistorydb',
            name='Message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
