# Generated by Django 4.2.6 on 2023-12-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0027_labprescriptionhistorydb_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labprescriptionhistorydb',
            name='Report',
            field=models.FileField(default='Pending', upload_to='Documents_Report'),
        ),
    ]
