# Generated by Django 4.2.6 on 2023-12-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0028_alter_labprescriptionhistorydb_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprescriptiondb',
            name='Doctor_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
