# Generated by Django 4.2.6 on 2023-12-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0030_medicinedb_doctor_name_patientdetailsdb_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprescriptionhistorydb',
            name='lab',
            field=models.FileField(default='Pending', upload_to=''),
        ),
    ]
