# Generated by Django 4.2.6 on 2023-12-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0032_rename_password_hospitalnewdb_h_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordb',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labprescriptiondb',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labprescriptionhistorydb',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labreportsdb',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinedb',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetailsdb',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
