# Generated by Django 4.2.6 on 2023-12-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0033_alter_doctordb_date_alter_labprescriptiondb_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdb',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patientdb',
            name='Username',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
