# Generated by Django 4.2.6 on 2023-12-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0034_patientdb_id_alter_patientdb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
