# Generated by Django 4.2.6 on 2023-12-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0035_alter_patientdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordb',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/doctor'),
        ),
        migrations.AlterField(
            model_name='hospitalnewdb',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/hospital'),
        ),
        migrations.AlterField(
            model_name='labprescriptionhistorydb',
            name='Report',
            field=models.FileField(default='Pending', upload_to='Report'),
        ),
        migrations.AlterField(
            model_name='labreportsdb',
            name='Report',
            field=models.FileField(blank=True, null=True, upload_to='Report'),
        ),
        migrations.AlterField(
            model_name='patientdb',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Patient/'),
        ),
    ]
